"""test commit

Revision ID: a8acbaeeb50b
Revises: 0d07ef5455f0
Create Date: 2025-10-31 15:20:29.438543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8acbaeeb50b'
down_revision = '0d07ef5455f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('serial', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message_source', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('message_key', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_trigger_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('data_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_object_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_class_types', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recording_id', sa.Integer(), nullable=False))
        # Give the foreign key a proper name
        batch_op.create_foreign_key(
            "fk_metadata_recording",  # <- constraint name
            'recordings',
            ['recording_id'],
            ['recording_id']
        )

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('snapshot_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_url', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.drop_constraint("fk_metadata_recording", type_='foreignkey')
        batch_op.drop_column('recording_id')
        batch_op.drop_column('data_class_types')
        batch_op.drop_column('data_object_id')
        batch_op.drop_column('data_active')
        batch_op.drop_column('data_trigger_time')
        batch_op.drop_column('message_key')
        batch_op.drop_column('message_source')
        batch_op.drop_column('serial')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
